### ISSUE TITLE
Missing Linux installation instructions

### ISSUE THREAD

**Issue by bmerry** [HSA-Libraries/Bolt#161]
After downloading the binary tarball for Linux and unpacking it, I find a directory with some stuff in it, but no instructions on installation. For example, should one copy include, lib and lib64 to /usr/local? Or is it intended that Bolt applications should set up -I and -L compiler flags to wherever one unpacked Bolt? Is any special care needed if one already has Boost (and no doubt a different version of Boost) installed to avoid version conflicts?

**Comment by jayavanth** [comment]
Hi bmerry, You just need to specify the path of includes and libraries using -I and -L paths. We recommend using Boost 1.55, which can be found in lib(64)/. Nevertheless, you can use older versions. Note that, we have tested only for Boost 1.52+.

**Comment by ravibanger** [comment]
Linux support added with release 1.1.
