### ISSUE TITLE
Bolt_1.2: bolt:cl::sort is hanging for higher odd buffer sizes with 1000 iterations.

### ISSUE THREAD

**Issue by jhkumar** [HSA-Libraries/Bolt#222]
If we run bolt::cl::sort for 1000 iterations by having higher odd buffer sizes like 2 power 23, 2 power 25,.. for double and float data type it is hanging. No issues with non powers of 2 and even buffer sizes like 2 power 24, 2 power 26..

**Comment by HSA-Libraries** [comment]
Fixed in Bolt 1.3
