### ISSUE TITLE
scatter_if in bolt::amp not possible?

### ISSUE THREAD

**Issue by briansp2020** [HSA-Libraries/Bolt#60]
Hi,
I'm studying Bolt and wanted to implement an example program that needs scatter_if operation (http://thrust.github.io/doc/group__scattering.html#ga1079bc05bcb3d4b5080f1e07444fee37). I started to port thrust scatter_if code, which uses permutation_iterator but came across this (https://groups.google.com/forum/#!topic/thrust-users/Xe2JkFy_hUk). The Google Group post claims that permutation_iterator in AMP kernel is not possible because of the restriction AMP put on the use of pointer in kernel (ie. restrict(amp)). Is this true? If so, is it possible to implement permutation_iterator in bolt::cl?

BTW, Bolt forum in AMD Dev Central does not seem to work correctly. It is set to private and my post there does not seem to go through. :(

**Comment by jayavanth** [comment]
Hi Brian,
The implementation of permutation_iterator in bolt::cl is underway. We'll need to investigate on implementation of permutation_iterator in AMP. I'll get back to you on that.

I saw that you could post on Bolt forums now. Were you not able to post at all? How did you resolve it?

**Comment by briansp2020** [comment]
Jay,
Thanks for the reply. I did not do anything on the Bolt forum. I suppose it took some time for the moderator to get to my post. Why is that forum kept private? I think more people would get involved it it was public as all the other forum spaces are.

Any way, do you have a target date for releasing scatter_if/permutation_iterator in bolt::cl?

**Comment by jayavanth** [comment]
Brian,
Yes. I think we should make it accessible to public, I'll discuss with the admin of the group.

scatter_if/permutation_iterator will be available in our 1.1 release i.e. by end of Aug tentatively.

**Comment by jayavanth** [comment]
Brian,
Scatter/Gather APIs are checked into develop branch for OpenCL. Note that we did not use permutation_iterator for this. We are figuring out a better way to do this. The current idea involves passing an extra buffer to the kernel consequently changing all OpenCL kernel. We'll be taking that up later.

**Comment by briansp2020** [comment]
Jay,
I used scatter_if to complete my radix sort example and it works well.
Thanks.
